### PR TITLE
Add Soundex Encoding

### PR DESCRIPTION
**Pull request by harrislineage**
Add option to display the Soundex encoding of Last Name Current and Last Name at Birth in .VITALS.

### CODE REVIEW

**Review by Lesko987 — APPROVED** [review]

**Comment by shogenapps** [comment]
I'm trying to test this out, but I can't see what it's doing (or what it's supposed to do)...  (Is it just me?)

**Comment by shogenapps** [comment]
Strangely, I'm now seeing the expected result for some people, but not many.  I put in the ID of an ancestor and I got the expected result.  I tried his family members' profiles and got good results, but when I went to lots of random profiles, I wasn't getting anything.  (Let me know where I'm going wrong.)

**Comment by harrislineage** [comment]
> but when I went to lots of random profiles, I wasn't getting anything.

When you can, shoot me a few ID's so I can check it out. It may be an error with trying to encode a URI encoded name.

**Comment by shogenapps** [comment]
> > but when I went to lots of random profiles, I wasn't getting anything.
> 
> When you can, shoot me a few ID's so I can check it out. It may be an error with trying to encode a URI encoded name.

Here's a few: Fournier-3159, Μπουντούρη-4, Moon-7352, Rea-287 .  These are just random profiles.

**Comment by harrislineage** [comment]
> Here's a few: Fournier-3159, Μπουντούρη-4, Moon-7352, Rea-287 . These are just random profiles.

- Fournier-3159, Moon-7352, and Rea-287 are working for me. Is nothing displaying at all for you, or just odd results?
- Μπουντούρη-4 is an encoding issue (investigating currently)

**Comment by harrislineage** [comment]
> * Μπουντούρη-4 is an encoding issue (investigating currently)

This should be fixed in the last commit. Μπουντούρη-4 should not return a Soundex code.

Since Soundex is an entirely English-oriented algorithm, it does not take into account characters from other languages. See the discussion at #155 for enhancements.

**Comment by shogenapps** [comment]
It's as I said - I'm getting no result for them or nearly anyone else.  It's quite bizarre.  It seems to work fine for any of my ancestors or cousins, but not for any other random profile.  For example, here's a cousin of mine where it's working fine - https://www.wikitree.com/wiki/Backhouse-663 - and here's another random Backhouse, where it's not working - https://www.wikitree.com/wiki/Backhouse-123.

**Comment by harrislineage** [comment]
> For example, here's a cousin of mine where it's working fine - https://www.wikitree.com/wiki/Backhouse-663 - and here's another random Backhouse, where it's not working - https://www.wikitree.com/wiki/Backhouse-123.

I tried disabling all other extensions, disabling all other features of the WikiTree extension, etc. This is quite strange ... everything is working as intended for me no matter what I choose.

@Lesko987 do you think can test for us? See if the Soundex shows for:
- Fournier-3159
- Moon-7352
- Rea-287
- Backhouse-663
- Backhouse-123

**Comment by Lesko987** [comment]
I installed the #162 version and All 5 examples work including me and [Backhouse-123](https://www.wikitree.com/wiki/Backhouse-123). I don-t really know what to do with that number, but it is there.

It works even on both lastnames and with ščž.
Jožefa Dovgan [D125] formerly Mahnič [M500]

And there are no errors in the console log. I use Latest Chrome on Windows.

But I don't know what to do with that number.

**Comment by harrislineage** [comment]
> I don't really know what to do with that number, but it is there.

No worries - this happens to be a US-centric thing for advanced genealogists. As long as it is displaying something, we should be good.

**Comment by shogenapps** [comment]
I think I see what's happening, and perhaps this is related to your having special 'team' powers.  
When I see the profiles of my ancestors and cousins, I'm seeing the private view.  Here, the title on the last name at birth and current last name are the titles that you are targeting ("Last Name at Birth" and "Current Last Name").  But I saw all those other profiles - the random ones - in the 'public view', and here, the title for those is different. It's "Click here for the surname index page".  I'm guessing that with your special access, you see every profile in the 'private view'?

**Comment by harrislineage** [comment]
> I'm guessing that with your special access, you see every profile in the 'private view'?

😒 I think you are right... Interesting that the title is changing depending on the view (though I see why they would). Taking a quick look, I may need to switch to the itemprop identification.

**Comment by jmegenealogy** [comment]
> > I'm guessing that with your special access, you see every profile in the 'private view'?
> 
> 😒 I think you are right... Interesting that the title is changing depending on the view (though I see why they would). Taking a quick look, I may need to switch to the itemprop identification.

Are you still wanting to work on this, or is it ready to merge in?

**Comment by harrislineage** [comment]
> Are you still wanting to work on this, or is it ready to merge in?

I am still holding on this.

**Pull request closed without merging**
