### PR TITLE
Rename mjs files to js

### PR DESCRIPTION
**Pull request by PeWu**
This change simplifies the project configuration and makes it more consistent.
@RobPavey introduced these changes alongside a larger change #90. We agreed to merge Rob's PR quicker and leave this file renaming for a subsequent PR.

### CODE REVIEW

**Comment by RobPavey** [comment]
I got your latest changes and this works for me locally.

I notice that you eliminated the dynamic module loading in agc_content in your previous jest change. Does this mean that we can't use any dynamic module loading in the extension?

**Comment by RobPavey** [comment]
I was hoping that we could leave agc/library/editbio.mjs completely untouched while I am maintaining AGC both in the existing wikitree-agc extension and in this extension so I can copy it back and forth if I need to do bug fixes. But changes are creeping in and now it is changing extension. I can work around it but it is slightly frustrating.

**Comment by PeWu** [comment]
I didn't change the dynamic loading in `agc_content`, only in the test file

**Comment by RobPavey** [comment]
> I didn't change the dynamic loading in agc_content, only in the test file

Sorry I misread that.

**Pull request merged**
