### PR TITLE
Add zip script

### PR DESCRIPTION
**Pull request by PeWu**
Run `npm run zip` to get a fresh `wikitree-browser-extension.zip` file

### CODE REVIEW

**Comment by shogenapps** [comment]
Did I do something wrong?
image

**Comment by PeWu** [comment]
Did you run `npm run build` first? The command assumes there is a `dist` folder.

Maybe to avoid confusion it would be better to run `npm run build` from the zip command, i.e.
`npm run build && cd dist && bestzip ...`

**Comment by shogenapps** [comment]
> Did you run `npm run build` first? The command assumes there is a `dist` folder.
> 
> Maybe to avoid confusion it would be better to run `npm run build` from the zip command, i.e. `npm run build && cd dist && bestzip ...`

No, I hadn't.  When I just did that now, it worked fine, but your new suggestion didn't. I got this. 
image

**Comment by shogenapps** [comment]
Are you going to update this to build and zip？

**Pull request merged**
