### PR TITLE
Add `zip-firefox` script

### PR DESCRIPTION
**Pull request by PeWu**
Run `npm run zip-firefox` to get a packaged Firefox extension

### CODE REVIEW

**Comment by RobPavey** [comment]
Just curious if this works for submitting a package to Firefox. For my extensions I have always built a .crx file which requires a .pem file.

The resulting .crx can be tested here: https://www.extensiontest.com/

**Comment by shogenapps** [comment]
I wanted this to submit to Firefox.  I used it and submitted the file, and it went through fine.

**Comment by RobPavey** [comment]
OK never mind then. I guess I have been doing more work that I needed all this time. I thought that because they say "Select .crx file" that it had to be a .crx file.

**Comment by RobPavey** [comment]
FYI I tried using a zip file (rather than a .crx) to release my latest version of Sourcer on Firefox. I'm on Mac and just did a compress. When I uploaded this it got a lot of warnings about .DS_Store files. So, I'm not sure if this would happen if someone tries to do a release of the WBE on Mac using this script.

**Pull request merged**
