### PR TITLE
Redesign the Options page a little

### PR DESCRIPTION
**Pull request by shogenapps**
Add a title;
Add the WT logo;
Add the WT header background;
Move the global on/off switch to the right

### CODE REVIEW

**Comment by RobPavey** [comment]
There is a lot of reformatting in this review. Mostly due to printWidth. I'm using a printWidth or 120 and it looks like Ian is using 80.

We need a decision on formatting rules or it makes it hard to review changes because of the reformatting.

**Comment by shogenapps** [comment]
> There is a lot of reformatting in this review. Mostly due to printWidth. I'm using a printWidth or 120 and it looks like Ian is using 80.
> 
> We need a decision on formatting rules or it makes it hard to review changes because of the reformatting.

Yes, it's 80. I'm using the default Prettier settings.  If there is a standard Prettier settings file that we should use, I'll be happy to use it.

**Comment by bcaseyrls** [comment]
The wikitree-dynamic-tree project has a .prettierrc file. It sets the printWidth to 120.

**Comment by shogenapps** [comment]
> The wikitree-dynamic-tree project has a .prettierrc file. It sets the printWidth to 120.

I'll use that, then.

**Comment by RobPavey** [comment]
> The wikitree-dynamic-tree project has a .prettierrc file. It sets the printWidth to 120.

Unfortunately the wikitree-dynamic-tree .prettier.rc contains a lot of other stuff that is not popular with the browser-extension team :(  Like an indentation of 4 spaces among other things.

Personally I would like to only change the printWidth and nothing else. I don't know how we reach agreement on this.

**Comment by bcaseyrls** [comment]
The two projects can have their own .prettierrc file. I was mostly suggesting that this project have one that everyone can use, with explicit choices rather than depending on defaults or each user's individual setup. The group here could certainly decide to use a different set of values.

**Comment by RobPavey** [comment]
@shogenapps Could you post a screenshot of your changes? I can't really visualize them from the code and I'm too lazy to stash my changes and switch to your branch for a minor change like this.

**Comment by shogenapps** [comment]
image

**Comment by RobPavey** [comment]
My 2 cents:
- Moving the toggle to the far right on the top line is good
- I don't personally like the rounded syle on the headings. I think it makes then look less modern and also more like a button
- Not sure about the color change. Maybe I just got used to the green I think a preferred ii

**Comment by shogenapps** [comment]
> My 2 cents:
> 
> * Moving the toggle to the far right on the top line is good
> * Adding logo is good
> * I don't personally like the rounded style on the headings. I think it makes then look less modern and also more like a button
> * Not sure about the color change. Maybe I just got used to the green but I think I preferred it

OK. Thanks.  I'll change it.

**Comment by shogenapps** [comment]
How about this one?
image

**Comment by jmegenealogy** [comment]
Hmmm. I do like the addition of the logo, and the placement of the toggle.

I wasn't a fan of the rounded look, and much prefer the non-rounded look. But the green border just doesn't seem right to me. Maybe if it's the darker "WikiTree" green? https://www.wikitree.com/css/examples.html

Actually, this might be a good thing to ask for opinions for in G2G. I'll link it in the feedback requests post.

**Comment by shogenapps** [comment]
> I wasn't a fan of the rounded look, and much prefer the non-rounded look. But the green border just doesn't seem right to me. Maybe if it's the darker "WikiTree" green? https://www.wikitree.com/css/examples.html
> 

This is with one of the dark greens from the style page.  Maybe it's better.

image

**Comment by RobPavey** [comment]
I think that beige color is fine for the top header (no need for green bottom border IMO) because it looks like the header on most wikitree pages.

For the categories I would go with a plain color like it was before. Either the really dark green used for WikiTree buttons with white text (but does that suggest a button?), or the pale green used for the "Green box" on the style page with black text.

**Comment by shogenapps** [comment]
> I think that beige color is fine for the top header (no need for green bottom border IMO) because it looks like the header on most wikitree pages.
> 
> For the categories I would go with a plain color like it was before. Either the really dark green used for WikiTree buttons with white text (but does that suggest a button?), or the pale green used for the "Green box" on the style page with black text.

Yes, I think that dark green with white text would suggest a button.  

I think this is what you're suggesting?
image

**Comment by RobPavey** [comment]
Yes that latest looks good to me !

**Comment by jmegenealogy** [comment]
I like that one much better too. I'm fine with this being merged.

**Review by Lesko987 — APPROVED** [review]

**Pull request merged**
