### PR TITLE
Use wikitree-js library for WikiTree API calls in randomProfile.js

### PR DESCRIPTION
**Pull request by PeWu**
The source for the wikitree-js library is at https://github.com/PeWu/wikitree-js

What do you think about moving this repository to the [wikitree](https://github.com/wikitree) GitHub organization?

### CODE REVIEW

**Comment by shogenapps** [comment]
I see no reason not to do this.  I haven't used it yet, but I'm sure it will be useful... 
Is there any reason not to do this?  I also have a function named getRelatives (I put it in common.js).  Would that be a problem?

**Comment by PeWu** [comment]
The getRelatives function can be replaced by a call to the library function that does the same. It doesn't have to be replaced immediately.

**Comment by PeWu** [comment]
I recreated the PR as #75

**Comment by jmegenealogy** [comment]
> The source for the wikitree-js library is at https://github.com/PeWu/wikitree-js
> 
> What do you think about moving this repository to the [wikitree](https://github.com/wikitree) GitHub organization?

@PeWu , would we do this by creating a fork of your repo, or would you transfer it to the WikiTree organization?

**Comment by PeWu** [comment]
> > The source for the wikitree-js library is at https://github.com/PeWu/wikitree-js
> > What do you think about moving this repository to the [wikitree](https://github.com/wikitree) GitHub organization?
> 
> @PeWu , would we do this by creating a fork of your repo, or would you transfer it to the WikiTree organization?

@jmegenealogy I suggest transferring the repo to the WikiTree organization.

**Pull request merged**
