### PR TITLE
Change the way features are registered

### PR DESCRIPTION
**Pull request by PeWu**
When adding a new feature:
- `src/options.js` file no longer needs to be modified
- feature's `name`, `id`, `description` and `category` are now defined in the feature source file, i.e. together with the feature
- feature code no longer has to call `chrome.storage.sync`

This PR is a suggestion with changes to `familyTimeline` and `printerFriendly` as examples. If everyone is OK with this change, I'll update other features and the documentation.

Redoing #63

### CODE REVIEW

**Review by Lesko987 — APPROVED** [review]

**Comment by RobPavey** [comment]
Please hold off on building on this as I have reworked all the options code and have a PR coming

**Comment by RobPavey** [comment]
I have also redesigned how features are registered as part of the options work I have been working on for a while.

It is going to take me some time to combine the two designs and it may not end up looking like this so, as I said above, please don't change any other features to use this system until I have reconciled the design.

**Comment by PeWu** [comment]
Rob, if it's easier for you, we can first revert my change.

**Comment by RobPavey** [comment]
If you can that would be great. You can then see if parts of your change are still desirable. I got some feedback on my changes from Ian - who wanted radio button support, so I'm implementing that and also cleaning up my changes. I will try to get a PR in today.

**Pull request merged**
