### PR TITLE
Convert AGC tests to use jest testing library

### PR DESCRIPTION
**Pull request by PeWu**
Remember to run `npm install` before running tests because new dependencies need to be installed.

Running tests: `npm test`

Other useful commands:
Run tests on each file save: `npm test -- --watch`
Run tests with more verbose output: `npm test -- --verbose`

To add tests to other features or core files, add files that end with `.test.js`.

More details about testing with jest: https://jestjs.io/

Sample output:
image

### CODE REVIEW

**Comment by PeWu** [comment]
@RobPavey please take a look

**Comment by RobPavey** [comment]
I will have a more detailed look at this tomorrow. Can I test this in your fork on the development branch?
Could you explain how to run the tests with arguments - like for a specific profile and variant?
Could you explain how to run a test in the debugger from vscode?
I guess this is a more "standard" way to do things but means I have to learn new stuff.

**Comment by PeWu** [comment]
You can clone my fork to test the changes.
```
git clone -b tests4 https://github.com/PeWu/wikitree-browser-extension.git
cd wikitree-browser-extension
npm install
npm test
```

Running a single test:
`npm test -- -t Zancher-1`

Command line arguments are documented here: https://jestjs.io/docs/cli (note that running with npm you need to pass the arguments after the double dash `--`)

I tried debugging in vscode and it works.
Option 1.
- Click "Run and Debug" icon on the left
- Click "JavaScript Debug Terminal"
- Run `npm test -- --runInBand`
Now you can add breakpoints and run the tests again to debug.

Option 2.
See https://jestjs.io/docs/troubleshooting#debugging-in-vs-code for details.
You can create a `launch.json` config file and then just click the "play" button to run tests.

Without `--runInBand` tests run in parallel making it more difficult to debug.

Go ahead and try breaking the tests. I tried some cases but you probably have some more interesting failure scenarios.

**Review by Lesko987 — APPROVED** [review]

**Comment by RobPavey** [comment]
I would have liked to have a chance to review this before it got merged in. If I disagree with changes should I now make a PR to change them?

**Pull request merged**
